In [ ]:
'''
Numpy: 파이썬에서 수학과 데이터 분석을 쉽게 할 수 있도록 도와주는 라이브러리
ndArray: 숫자를 여러 차원으로 저장할 수 있는 배열
Numpy로 할 수 있는 것들
- 숫자 묶음 생성
- 평균, 합계, 최대값
- 배열 덧셈, 곱셈
- 2차원표 (행렬)
'''

1


In [2]:
# 일반 리스트
a = [1, 2, 3]
b = [4, 5, 6]
print(a + b)

[1, 2, 3, 4, 5, 6]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# np.array([1, 2, 3]) # 리스트처럼 보이지만 실제로는 수학용 배열, 모든 원소가 같은 타입

arr1 = np.array([1, 2, 3, 4])

In [ ]:
import numpy as np

np.array([1, 2, 3, 4])

arr1 = np.array([1,2,3,4])
arr2 = [1,2,3,4]

# class 'numpy.ndarray' -> 
print(type(arr1))
print(type(arr2))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
# 1차원 배열 : 숫자가 한 줄로 늘어선 형태
# 2차원 배열 : 숫자가 가로와 세로로 된 표 모양


# 2차원 ndarray 생성
# 1차원 배열 두개가 리스트로 묶인 형태 -> 2차원 배열

arr2 = np.array([[1, 2, 3,4],
                [5, 6, 7, 8]])

arr3 = np.array([[[1, 2, 3, 4], [1, 2, 3, 4]],
                [[1, 2, 3, 4], [1, 2, 3, 4]]])

print(arr2)

print('\n\n\n\n' arr3)

[[1 2 3 4]
 [5 6 7 8]]




 [[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]


In [8]:
a = np.array([1,2,3,4])

print(a+1)
print(a * 2)
print(a ** 2)

[2 3 4 5]
[2 4 6 8]
[ 1  4  9 16]


In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2, 3,4],
                [5, 6, 7, 8]])
arr3 = np.array([[[1, 2, 3, 4], [1, 2, 3, 4]],
                [[1, 2, 3, 4], [1, 2, 3, 4]]])

# ndim : 배열의 차원 수
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# shape : 배열의 형태(배열 구조를 튜플로 보여줌)
# (총 개수, 행 개수, 열 개수)
print(arr1.shape) # 숫자 4개가 있는 한 줄
print(arr2.shape) # 2줄, 각 줄에 4칸
print(arr3.shape) # 2장(층), 각 장마다 2줄 각 줄에 4칸

# size : 배열 요소의 총 개수
print(arr1.size) # 4
print(arr2.size) # 2 * 4 = 8
print(arr3.size) # 2 * 2 * 4 = 16

# dtype : 배열 요소의 데이터 타입
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

# itemsize : 배열 원소 하나가 차지하는 메모리 크기
print(arr1.itemsize)
print(arr2.itemsize)
print(arr3.itemsize)

# data : 배열의 실제 데이터가 저장된 메모리 버퍼(buffer)
print(arr1.data)
print(arr2.data)
print(arr3.data)



1
2
3
(4,)
(2, 4)
(2, 2, 4)
4
8
16
int64
int64
int64
8
8
8
